spring:
  application:
    name: BistuTrade
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 

logging:
  config: classpath:static/logger/log4j2-spring.xml